
ForeverProbeDB = {
["combatLog"] = {
["eventFired"] = 0,
["readerPresent"] = false,
["count"] = 0,
["registered"] = false,
["inCombatCount"] = 0,
["samples"] = {
},
["registrationForbidden"] = "measured 2026-09-18: ADDON_ACTION_FORBIDDEN at load, out of combat",
["subevents"] = {
},
},
["secrecy"] = {
["outofcombat"] = {
["combatLogRestricted"] = "true",
["chatMessagingLockdown"] = "false",
["addonRestrictionState"] = "0",
["gates"] = {
["ShouldUnitThreatStateBeSecret"] = "false",
["ShouldUnitHealthMaxBeSecret"] = "false",
["ShouldUnitPowerBeSecret"] = "true",
["ShouldAurasBeSecret"] = "false",
["ShouldUnitIdentityBeSecret"] = "false",
["CanCompareUnitTokens"] = "true",
["ShouldActionCooldownBeSecret"] = "false",
["ShouldUnitThreatValuesBeSecret"] = "true",
["ShouldUnitSpellCastBeSecret"] = "false",
["ShouldCooldownsBeSecret"] = "false",
["ShouldUnitStatsBeSecret"] = "false",
["HasSecretRestrictions"] = "true",
},
["addonMessagesRestricted"] = "true",
["gateArgs"] = {
["ShouldUnitThreatStateBeSecret"] = "(\"player\")",
["ShouldUnitHealthMaxBeSecret"] = "(\"player\")",
["ShouldUnitPowerBeSecret"] = "(\"player\")",
["ShouldAurasBeSecret"] = "()",
["ShouldUnitIdentityBeSecret"] = "(\"player\")",
["CanCompareUnitTokens"] = "(\"player\", 1)",
["ShouldActionCooldownBeSecret"] = "(1)",
["ShouldUnitThreatValuesBeSecret"] = "(\"player\", 1)",
["ShouldUnitSpellCastBeSecret"] = "(\"player\", 1)",
["ShouldCooldownsBeSecret"] = "()",
["ShouldUnitStatsBeSecret"] = "()",
["HasSecretRestrictions"] = "()",
},
["addonRestrictionActive"] = "false",
["addonRestrictionActiveArg"] = "(addonName)",
["addonRestrictionStateArg"] = "(addonName)",
["inCombat"] = false,
},
},
["blockLog"] = {
{
["addon"] = "ForeverProbe",
["test"] = "UseAction(slot1)",
["event"] = "ADDON_ACTION_FORBIDDEN",
["func"] = "UseAction()",
},
},
["registerBlocked"] = {
},
["bridge"] = {
["loads"] = 1,
},
["actions"] = {
["outofcombat"] = {
["tests"] = {
["EditMacro"] = {
["ok"] = true,
["allowed"] = true,
},
["SecureBtn:SetAttribute"] = {
["ok"] = true,
["allowed"] = true,
},
["UseAction(slot1)"] = {
["ok"] = true,
["allowed"] = false,
["blockEvents"] = {
"ADDON_ACTION_FORBIDDEN:UseAction()",
},
},
["CastSpellByName"] = {
["ok"] = true,
["allowed"] = true,
},
["SetOverrideBindingClick"] = {
["ok"] = true,
["allowed"] = true,
},
},
["reads"] = {
["spellCooldownStart"] = "nil",
["targetCasting"] = "NO TARGET",
["playerAura1"] = "Devotion Aura",
["playerPower"] = "<SECRET>",
["targetHealth"] = "NO TARGET",
["combatLogAPI"] = "ABSENT",
["targetAura1"] = "NO TARGET",
},
["inCombat"] = false,
},
},
["video"] = {
["outOfCombat"] = {
["displayMode"] = {
["gxMonitor"] = "0",
["windowSize"] = "1920x1080",
["gxWindow"] = "nil",
["gxWindowedResolution"] = "auto",
["gxFullscreenResolution"] = "auto",
["gxMaximize"] = "1",
},
["cvars"] = {
["gxContrast"] = {
["name"] = "gxContrast",
["present"] = false,
},
["Contrast"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "50.000000",
["storedServerAccount"] = false,
["value"] = "50.000000",
["name"] = "Contrast",
},
["Gamma"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "1.000000",
["storedServerAccount"] = false,
["value"] = "1.000000",
["name"] = "Gamma",
},
["useHDRPeakBrightness"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "0",
["storedServerAccount"] = false,
["value"] = "0",
["name"] = "useHDRPeakBrightness",
},
["useHDRBrightness"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "0",
["storedServerAccount"] = false,
["value"] = "0",
["name"] = "useHDRBrightness",
},
["questTextContrast"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "0",
["storedServerAccount"] = false,
["value"] = "4",
["name"] = "questTextContrast",
},
["gxBrightness"] = {
["name"] = "gxBrightness",
["present"] = false,
},
["gxGamma"] = {
["name"] = "gxGamma",
["present"] = false,
},
["Brightness"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "50.000000",
["storedServerAccount"] = false,
["value"] = "50.000000",
["name"] = "Brightness",
},
["HDRPeakBrightness"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "400",
["storedServerAccount"] = false,
["value"] = "400",
["name"] = "HDRPeakBrightness",
},
["HDRBrightness"] = {
["lockedFromUser"] = false,
["present"] = true,
["writable"] = true,
["readOnly"] = false,
["storedServerCharacter"] = false,
["secure"] = false,
["default"] = "203",
["storedServerAccount"] = false,
["value"] = "203",
["name"] = "HDRBrightness",
},
},
["discovery"] = {
["matches"] = {
"Brightness",
"Contrast",
"Gamma",
"HDRBrightness",
"HDRPeakBrightness",
"questTextContrast",
"useHDRBrightness",
"useHDRPeakBrightness",
},
["total"] = 1902,
["entryShape"] = "category,command,commandType,help,scriptContents,scriptParameters",
},
["writes"] = {
["Brightness via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 50,
["target"] = 45,
["allowed"] = true,
["restoredTo"] = "50.000000",
["readBack"] = "45.0000",
},
["Contrast via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 50,
["target"] = 45,
["allowed"] = true,
["restoredTo"] = "50.000000",
["readBack"] = "45.0000",
},
["HDRBrightness via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 203,
["target"] = 182.7,
["allowed"] = true,
["restoredTo"] = "203",
["readBack"] = "182.7000",
},
["useHDRPeakBrightness via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 0,
["target"] = 0.1,
["allowed"] = true,
["restoredTo"] = "0",
["readBack"] = "0.1000",
},
["useHDRPeakBrightness via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 0,
["target"] = 0.1,
["allowed"] = true,
["restoredTo"] = "0",
["readBack"] = "0.1000",
},
["questTextContrast via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 4,
["target"] = 3.6,
["allowed"] = true,
["restoredTo"] = "4",
["readBack"] = "3.6000",
},
["useHDRBrightness via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 0,
["target"] = 0.1,
["allowed"] = true,
["restoredTo"] = "0",
["readBack"] = "0.1000",
},
["HDRPeakBrightness via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 400,
["target"] = 360,
["allowed"] = true,
["restoredTo"] = "400",
["readBack"] = "360.0000",
},
["questTextContrast via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 4,
["target"] = 3.6,
["allowed"] = true,
["restoredTo"] = "4",
["readBack"] = "3.6000",
},
["Gamma via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 1,
["target"] = 0.9,
["allowed"] = true,
["restoredTo"] = "1.000000",
["readBack"] = "0.9000",
},
["HDRPeakBrightness via SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "SetCVar",
["callOk"] = true,
["from"] = 400,
["target"] = 360,
["allowed"] = true,
["restoredTo"] = "400",
["readBack"] = "360.0000",
},
["Gamma via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 1,
["target"] = 0.9,
["allowed"] = true,
["restoredTo"] = "1.000000",
["readBack"] = "0.9000",
},
["Brightness via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 50,
["target"] = 45,
["allowed"] = true,
["restoredTo"] = "50.000000",
["readBack"] = "45.0000",
},
["HDRBrightness via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 203,
["target"] = 182.7,
["allowed"] = true,
["restoredTo"] = "203",
["readBack"] = "182.7000",
},
["useHDRBrightness via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 0,
["target"] = 0.1,
["allowed"] = true,
["restoredTo"] = "0",
["readBack"] = "0.1000",
},
["Contrast via C_CVar.SetCVar"] = {
["returned"] = "true",
["tookEffect"] = true,
["via"] = "C_CVar.SetCVar",
["callOk"] = true,
["from"] = 50,
["target"] = 45,
["allowed"] = true,
["restoredTo"] = "50.000000",
["readBack"] = "45.0000",
},
},
["setterPresent"] = {
["C_CVar.SetCVar"] = true,
["SetCVar"] = true,
},
["inCombat"] = false,
},
["ramp"] = {
["maxDelta"] = 0.03100000135600567,
["elapsed"] = 4.005000201053917,
["frames"] = 443,
["writeFailures"] = 0,
["minDelta"] = 0.00800000037997961,
["amplitude"] = 20,
["base"] = 50,
["writes"] = 442,
["cvar"] = "Brightness",
["inCombat"] = false,
},
},
}
