
ForeverProbeDB = {
["port"] = {
["projectConstants"] = {
{
["key"] = "WOW_PROJECT_CLASSIC",
["value"] = "2",
},
{
["key"] = "WOW_PROJECT_ID",
["value"] = "1",
},
{
["key"] = "WOW_PROJECT_MAINLINE",
["value"] = "1",
},
},
["interfaceFormulaHolds"] = true,
["interfaceDerived"] = 16001,
["identity"] = {
["GetRealmID"] = "4618",
["GetCVar(realmList)"] = "nil",
["GetCurrentRegion"] = "90",
["GetNormalizedRealmName"] = "ClassicBetaPvE",
["GetCurrentRegionName"] = "",
["UnitFullName"] = "Abla Imperial",
["UnitGUID"] = "Player-4618-00C20142",
["UnitName"] = "Abla Imperial",
["GetRealmName"] = "Classic Beta PvE",
},
["buildDate"] = "Sep 17 2026",
["version"] = "1.60.1",
["nameplates"] = {
["nameplate1"] = "nil",
["focus"] = "nil",
["target"] = "frame",
["targettarget"] = "RAISED: bad argument #1 to '?' (Target-of-target unit tokens are not allowed for this call. - Usage: local nameplate = C_NamePlate.GetNamePlateForUnit(unitToken [, includeForbidden]))",
["mouseover"] = "nil",
},
["gameTypeSymbols"] = {
"C_GameRules (table)",
"CamelotBankPanelItemButtonMixin (table)",
"GameRulesUtil (table)",
"GetNumWarGameTypes (function)",
"GetSelectedWarGameType (function)",
"GetWarGameTypeInfo (function)",
"SetSelectedWarGameType (function)",
},
["build"] = "69913",
["interface"] = "16001",
},
["docsSecrets"] = {
["byKind"] = {
["Function"] = 4076,
["Payload"] = 832,
["Return"] = 20,
["Event"] = 93,
["Argument"] = 50,
["Field"] = 74,
},
["byKey"] = {
["NeverSecret"] = {
["present"] = 942,
["truthy"] = 942,
},
["SecretWhenUnitPowerRestricted"] = {
["present"] = 7,
["truthy"] = 7,
},
["SecretWhenUnitAuraRestricted"] = {
["present"] = 22,
["truthy"] = 22,
},
["SecretPayloads"] = {
["present"] = 7,
["truthy"] = 7,
},
["SecretWhenUnitIdentityRestricted"] = {
["present"] = 34,
["truthy"] = 34,
},
["ConditionalSecret"] = {
["present"] = 19,
["truthy"] = 19,
},
["SecretArguments"] = {
["present"] = 3929,
["truthy"] = 3929,
},
["SecretValue"] = {
["present"] = 12,
["truthy"] = 12,
},
["SecretWhenUnitThreatValuesRestricted"] = {
["present"] = 2,
["truthy"] = 2,
},
["ConstSecretAccessor"] = {
["present"] = 46,
["truthy"] = 46,
},
["SecretWhenAnchoringSecret"] = {
["present"] = 23,
["truthy"] = 23,
},
["SecretWhenCurveSecret"] = {
["present"] = 8,
["truthy"] = 8,
},
["SecretWhenInCombat"] = {
["present"] = 4,
["truthy"] = 4,
},
["ConditionalSecretContents"] = {
["present"] = 1,
["truthy"] = 1,
},
["RequiresNonSecretAura"] = {
["present"] = 3,
["truthy"] = 3,
},
["SecretWhenNumericFormatterSecret"] = {
["present"] = 3,
["truthy"] = 3,
},
["SecretWhenUnitHealthMaxRestricted"] = {
["present"] = 1,
["truthy"] = 1,
},
["SecretArgumentsAddAspect"] = {
["present"] = 55,
["truthy"] = 55,
},
["SecretWhenUnitComparisonRestricted"] = {
["present"] = 1,
["truthy"] = 1,
},
["SecretWhenAurasRestricted"] = {
["present"] = 1,
["truthy"] = 1,
},
["NeverSecretContents"] = {
["present"] = 2,
["truthy"] = 2,
},
["SecretInActivePvPMatch"] = {
["present"] = 2,
["truthy"] = 2,
},
["SecretInChatMessagingLockdown"] = {
["present"] = 99,
["truthy"] = 99,
},
["SecretWhenLuaTableHasSecretKeys"] = {
["present"] = 3,
["truthy"] = 3,
},
["SecretWhenEncounterEvent"] = {
["present"] = 3,
["truthy"] = 3,
},
["SecretReturnsForAspect"] = {
["present"] = 92,
["truthy"] = 92,
},
["SecretWhenUnitNameIdentityRestricted"] = {
["present"] = 1,
["truthy"] = 1,
},
["SecretWhenUnitThreatStateRestricted"] = {
["present"] = 2,
["truthy"] = 2,
},
["SecretReturns"] = {
["present"] = 18,
["truthy"] = 18,
},
["SecretWhenUnitStatsRestricted"] = {
["present"] = 58,
["truthy"] = 58,
},
["SecretWhenLossOfControlInfoRestricted"] = {
["present"] = 3,
["truthy"] = 3,
},
["SecretWhenUnitPossessionRestricted"] = {
["present"] = 2,
["truthy"] = 2,
},
["SecretWhenUnitPowerMaxRestricted"] = {
["present"] = 1,
["truthy"] = 1,
},
["ReturnsNeverSecret"] = {
["present"] = 16,
["truthy"] = 16,
},
["SecretWhenUnitSpellCastRestricted"] = {
["present"] = 21,
["truthy"] = 21,
},
["SecretWhenCooldownsRestricted"] = {
["present"] = 15,
["truthy"] = 15,
},
["SecretWhenTotemSlotSecret"] = {
["present"] = 2,
["truthy"] = 2,
},
},
["carrying"] = 5145,
["entries"] = 29416,
},
["savedVars"] = {
["order"] = "unknown",
["phases"] = {
{
["phase"] = "file-scope",
["globals"] = {
{
["type"] = "nil",
["name"] = "ForeverProbeDB",
["idiom"] = "file-scope `X = X or {}`",
},
{
["type"] = "nil",
["name"] = "ForeverProbeBind",
["idiom"] = "bound on ADDON_LOADED",
},
{
["type"] = "nil",
["name"] = "ForeverProbeClobber",
["idiom"] = "file-scope reassignment",
},
{
["type"] = "nil",
["name"] = "ForeverProbeChar",
["idiom"] = "per-character, on ADDON_LOADED",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "ADDON_LOADED-before-bind",
["globals"] = {
{
["idiom"] = "file-scope `X = X or {}`",
["addr"] = "table: 0000024144513870",
["name"] = "ForeverProbeDB",
["keys"] = 0,
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeBind",
["idiom"] = "bound on ADDON_LOADED",
},
{
["idiom"] = "file-scope reassignment",
["addr"] = "table: 000002414448BBB0",
["name"] = "ForeverProbeClobber",
["keys"] = 1,
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeChar",
["idiom"] = "per-character, on ADDON_LOADED",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "ADDON_LOADED-after-bind",
["globals"] = {
{
["idiom"] = "file-scope `X = X or {}`",
["addr"] = "table: 0000024144513870",
["name"] = "ForeverProbeDB",
["keys"] = 0,
["type"] = "table",
},
{
["idiom"] = "bound on ADDON_LOADED",
["addr"] = "table: 000002414451ADE0",
["name"] = "ForeverProbeBind",
["stampedAt"] = "ADDON_LOADED",
["keys"] = 3,
["token"] = "121740-3053",
["session"] = 1,
["type"] = "table",
},
{
["idiom"] = "file-scope reassignment",
["addr"] = "table: 000002414448BBB0",
["name"] = "ForeverProbeClobber",
["stampedAt"] = "ADDON_LOADED",
["keys"] = 4,
["token"] = "121740-3053",
["session"] = 1,
["type"] = "table",
},
{
["idiom"] = "per-character, on ADDON_LOADED",
["addr"] = "table: 000002414451AE30",
["name"] = "ForeverProbeChar",
["stampedAt"] = "ADDON_LOADED",
["keys"] = 3,
["token"] = "121740-3053",
["session"] = 1,
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "PLAYER_LOGIN",
["globals"] = {
{
["idiom"] = "file-scope `X = X or {}`",
["addr"] = "table: 0000024144513870",
["name"] = "ForeverProbeDB",
["keys"] = 0,
["type"] = "table",
},
{
["idiom"] = "bound on ADDON_LOADED",
["addr"] = "table: 000002414451ADE0",
["name"] = "ForeverProbeBind",
["stampedAt"] = "ADDON_LOADED",
["keys"] = 3,
["token"] = "121740-3053",
["session"] = 1,
["type"] = "table",
},
{
["idiom"] = "file-scope reassignment",
["addr"] = "table: 000002414448BBB0",
["name"] = "ForeverProbeClobber",
["stampedAt"] = "ADDON_LOADED",
["keys"] = 4,
["token"] = "121740-3053",
["session"] = 1,
["type"] = "table",
},
{
["idiom"] = "per-character, on ADDON_LOADED",
["addr"] = "table: 000002414451AE30",
["name"] = "ForeverProbeChar",
["stampedAt"] = "ADDON_LOADED",
["keys"] = 3,
["token"] = "121740-3053",
["session"] = 1,
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "PLAYER_ENTERING_WORLD",
["globals"] = {
{
["idiom"] = "file-scope `X = X or {}`",
["addr"] = "table: 0000024144513870",
["name"] = "ForeverProbeDB",
["keys"] = 1,
["type"] = "table",
},
{
["idiom"] = "bound on ADDON_LOADED",
["addr"] = "table: 000002414451ADE0",
["name"] = "ForeverProbeBind",
["stampedAt"] = "PLAYER_LOGIN",
["keys"] = 4,
["token"] = "121740-3053",
["session"] = 2,
["type"] = "table",
},
{
["idiom"] = "file-scope reassignment",
["addr"] = "table: 000002414448BBB0",
["name"] = "ForeverProbeClobber",
["stampedAt"] = "PLAYER_LOGIN",
["keys"] = 5,
["token"] = "121740-3053",
["session"] = 2,
["type"] = "table",
},
{
["idiom"] = "per-character, on ADDON_LOADED",
["addr"] = "table: 000002414451AE30",
["name"] = "ForeverProbeChar",
["stampedAt"] = "PLAYER_LOGIN",
["keys"] = 4,
["token"] = "121740-3053",
["session"] = 2,
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
},
["tokenWrittenThisSession"] = "121740-3053",
},
["external"] = {
["loads"] = 1,
},
["secretModes"] = {
["outOfCombat"] = {
["player.UnitClass"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitHealthMax"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["player.UnitPower"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
["player.UnitGUID"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitPowerMax"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["player.UnitLevel"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["player.UnitName"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitHealth"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
},
["inCombat"] = {
["target.UnitClass"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitPowerMax"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["target.UnitHealthMax"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
["target.UnitGUID"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["target.UnitName"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["target.UnitPower"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
["target.UnitPowerMax"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
["target.UnitLevel"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["target.UnitHealth"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
["player.UnitHealthMax"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["player.UnitPower"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
["player.UnitClass"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitGUID"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitLevel"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = true,
["equal"] = true,
["arith"] = true,
["tostring"] = true,
["isSecret"] = false,
["concat"] = true,
},
["player.UnitName"] = {
["type"] = "string",
["concat"] = true,
["equal"] = true,
["tostring"] = true,
["isSecret"] = false,
["tostringSecret"] = false,
},
["player.UnitHealth"] = {
["type"] = "number",
["concat"] = true,
["equal"] = false,
["tostring"] = true,
["isSecret"] = true,
["tostringSecret"] = true,
},
},
},
}
ForeverProbeBind = {
["token"] = "121740-3053",
["previousToken"] = "121740-3053",
["session"] = 3,
["stampedAt"] = "PLAYER_ENTERING_WORLD",
}
ForeverProbeClobber = {
["createdAt"] = "file-scope",
["token"] = "121740-3053",
["stampedAt"] = "PLAYER_ENTERING_WORLD",
["session"] = 3,
["previousToken"] = "121740-3053",
}
ForeverProbeSeed = nil
