
ForeverProbeDB = {
["savedVars"] = {
["order"] = "unknown",
["phases"] = {
{
["phase"] = "file-scope",
["globals"] = {
{
["type"] = "nil",
["name"] = "ForeverProbeDB",
["idiom"] = "file-scope `X = X or {}`",
},
{
["type"] = "nil",
["name"] = "ForeverProbeBind",
["idiom"] = "bound on ADDON_LOADED",
},
{
["type"] = "nil",
["name"] = "ForeverProbeClobber",
["idiom"] = "file-scope reassignment",
},
{
["type"] = "nil",
["name"] = "ForeverProbeChar",
["idiom"] = "per-character, on ADDON_LOADED",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "ADDON_LOADED-before-bind",
["globals"] = {
{
["addr"] = "table: 000001C3B20FC100",
["name"] = "ForeverProbeDB",
["keys"] = 0,
["idiom"] = "file-scope `X = X or {}`",
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeBind",
["idiom"] = "bound on ADDON_LOADED",
},
{
["addr"] = "table: 000001C3B20EAF00",
["name"] = "ForeverProbeClobber",
["keys"] = 1,
["idiom"] = "file-scope reassignment",
["type"] = "table",
},
{
["type"] = "nil",
["name"] = "ForeverProbeChar",
["idiom"] = "per-character, on ADDON_LOADED",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "ADDON_LOADED-after-bind",
["globals"] = {
{
["addr"] = "table: 000001C3B20FC100",
["name"] = "ForeverProbeDB",
["keys"] = 0,
["idiom"] = "file-scope `X = X or {}`",
["type"] = "table",
},
{
["type"] = "table",
["stampedAt"] = "ADDON_LOADED",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B2152C60",
["name"] = "ForeverProbeBind",
["keys"] = 5,
["idiom"] = "bound on ADDON_LOADED",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "table",
["stampedAt"] = "ADDON_LOADED",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B20EAF00",
["name"] = "ForeverProbeClobber",
["keys"] = 6,
["idiom"] = "file-scope reassignment",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "table",
["stampedAt"] = "ADDON_LOADED",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B2152CB0",
["name"] = "ForeverProbeChar",
["keys"] = 5,
["idiom"] = "per-character, on ADDON_LOADED",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "PLAYER_LOGIN",
["globals"] = {
{
["addr"] = "table: 000001C3B20FC100",
["name"] = "ForeverProbeDB",
["keys"] = 0,
["idiom"] = "file-scope `X = X or {}`",
["type"] = "table",
},
{
["type"] = "table",
["stampedAt"] = "ADDON_LOADED",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B2152C60",
["name"] = "ForeverProbeBind",
["keys"] = 5,
["idiom"] = "bound on ADDON_LOADED",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "table",
["stampedAt"] = "ADDON_LOADED",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B20EAF00",
["name"] = "ForeverProbeClobber",
["keys"] = 6,
["idiom"] = "file-scope reassignment",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "table",
["stampedAt"] = "ADDON_LOADED",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B2152CB0",
["name"] = "ForeverProbeChar",
["keys"] = 5,
["idiom"] = "per-character, on ADDON_LOADED",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
{
["phase"] = "PLAYER_ENTERING_WORLD",
["globals"] = {
{
["addr"] = "table: 000001C3B20FC100",
["name"] = "ForeverProbeDB",
["keys"] = 1,
["idiom"] = "file-scope `X = X or {}`",
["type"] = "table",
},
{
["type"] = "table",
["stampedAt"] = "PLAYER_LOGIN",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B2152C60",
["name"] = "ForeverProbeBind",
["keys"] = 5,
["idiom"] = "bound on ADDON_LOADED",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "table",
["stampedAt"] = "PLAYER_LOGIN",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B20EAF00",
["name"] = "ForeverProbeClobber",
["keys"] = 6,
["idiom"] = "file-scope reassignment",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "table",
["stampedAt"] = "PLAYER_LOGIN",
["restoredSession"] = 0,
["addr"] = "table: 000001C3B2152CB0",
["name"] = "ForeverProbeChar",
["keys"] = 5,
["idiom"] = "per-character, on ADDON_LOADED",
["session"] = 1,
["token"] = "132025-1378",
},
{
["type"] = "nil",
["name"] = "ForeverProbeSeed",
["idiom"] = "written from outside the client",
},
},
},
},
["tokenWrittenThisSession"] = "132025-1378",
},
["external"] = {
["loads"] = 1,
},
["port"] = {
["projectConstants"] = {
{
["key"] = "WOW_PROJECT_CLASSIC",
["value"] = "2",
},
{
["key"] = "WOW_PROJECT_ID",
["value"] = "1",
},
{
["key"] = "WOW_PROJECT_MAINLINE",
["value"] = "1",
},
},
["interfaceFormulaHolds"] = true,
["interfaceDerived"] = 16001,
["identity"] = {
["GetRealmID"] = "4618",
["GetCVar(realmList)"] = "nil",
["GetCurrentRegion"] = "90",
["GetNormalizedRealmName"] = "ClassicBetaPvE",
["GetCurrentRegionName"] = "",
["UnitFullName"] = "Abla Imperial / ClassicBetaPvE",
["UnitGUID"] = "Player-4618-00C20142",
["UnitName"] = "Abla Imperial",
["GetRealmName"] = "Classic Beta PvE",
},
["buildDate"] = "Sep 17 2026",
["version"] = "1.60.1",
["realmIdentity"] = {
["GetRealmID"] = {
["second"] = "nil",
["first"] = "4618",
},
["GetRealmName"] = {
["second"] = "nil",
["first"] = "Classic Beta PvE",
},
["UnitFullName"] = {
["second"] = "ClassicBetaPvE",
["first"] = "Abla Imperial",
},
["GetCurrentRegion"] = {
["second"] = "nil",
["first"] = "90",
},
["UnitName"] = {
["second"] = "nil",
["first"] = "Abla Imperial",
},
["UnitGUID"] = {
["second"] = "nil",
["first"] = "Player-4618-00C20142",
},
["GetCurrentRegionName"] = {
["second"] = "nil",
["first"] = "",
},
["GetNormalizedRealmName"] = {
["second"] = "nil",
["first"] = "ClassicBetaPvE",
},
},
["nameplates"] = {
["nameplate1"] = "frame",
["focus"] = "nil",
["target"] = "frame",
["targettarget"] = "RAISED: bad argument #1 to '?' (Target-of-target unit tokens are not allowed for this call. - Usage: local nameplate = C_NamePlate.GetNamePlateForUnit(unitToken [, includeForbidden]))",
["mouseover"] = "nil",
},
["gameTypeSymbols"] = {
"C_GameRules (table)",
"CamelotBankPanelItemButtonMixin (table)",
"GameRulesUtil (table)",
"GetNumWarGameTypes (function)",
"GetSelectedWarGameType (function)",
"GetWarGameTypeInfo (function)",
"SetSelectedWarGameType (function)",
},
["build"] = "69913",
["interface"] = "16001",
},
["secretModes"] = {
["outOfCombat"] = {
["target.UnitClass"] = {
["tostringSecret"] = false,
["type"] = "string",
["compare"] = "n/a",
["equal"] = "ok",
["arith"] = "n/a",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["player.UnitPowerMax"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = "ok",
["equal"] = "ok",
["arith"] = "ok",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["target.UnitHealthMax"] = {
["tostringSecret"] = true,
["type"] = "number",
["compare"] = "threw",
["equal"] = "threw",
["arith"] = "threw",
["tostring"] = true,
["isSecret"] = true,
["concat"] = "ok",
},
["target.UnitGUID"] = {
["tostringSecret"] = false,
["type"] = "string",
["compare"] = "n/a",
["equal"] = "ok",
["arith"] = "n/a",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["target.UnitName"] = {
["tostringSecret"] = false,
["type"] = "string",
["compare"] = "n/a",
["equal"] = "ok",
["arith"] = "n/a",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["target.UnitPower"] = {
["tostringSecret"] = true,
["type"] = "number",
["compare"] = "threw",
["equal"] = "threw",
["arith"] = "threw",
["tostring"] = true,
["isSecret"] = true,
["concat"] = "ok",
},
["target.UnitPowerMax"] = {
["tostringSecret"] = true,
["type"] = "number",
["compare"] = "threw",
["equal"] = "threw",
["arith"] = "threw",
["tostring"] = true,
["isSecret"] = true,
["concat"] = "ok",
},
["target.UnitLevel"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = "ok",
["equal"] = "ok",
["arith"] = "ok",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["target.UnitHealth"] = {
["tostringSecret"] = true,
["type"] = "number",
["compare"] = "threw",
["equal"] = "threw",
["arith"] = "threw",
["tostring"] = true,
["isSecret"] = true,
["concat"] = "ok",
},
["player.UnitHealthMax"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = "ok",
["equal"] = "ok",
["arith"] = "ok",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["player.UnitPower"] = {
["tostringSecret"] = true,
["type"] = "number",
["compare"] = "threw",
["equal"] = "threw",
["arith"] = "threw",
["tostring"] = true,
["isSecret"] = true,
["concat"] = "ok",
},
["player.UnitClass"] = {
["tostringSecret"] = false,
["type"] = "string",
["compare"] = "n/a",
["equal"] = "ok",
["arith"] = "n/a",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["player.UnitGUID"] = {
["tostringSecret"] = false,
["type"] = "string",
["compare"] = "n/a",
["equal"] = "ok",
["arith"] = "n/a",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["player.UnitLevel"] = {
["tostringSecret"] = false,
["type"] = "number",
["compare"] = "ok",
["equal"] = "ok",
["arith"] = "ok",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["player.UnitName"] = {
["tostringSecret"] = false,
["type"] = "string",
["compare"] = "n/a",
["equal"] = "ok",
["arith"] = "n/a",
["tostring"] = true,
["isSecret"] = false,
["concat"] = "ok",
},
["player.UnitHealth"] = {
["tostringSecret"] = true,
["type"] = "number",
["compare"] = "threw",
["equal"] = "threw",
["arith"] = "threw",
["tostring"] = true,
["isSecret"] = true,
["concat"] = "ok",
},
},
},
}
ForeverProbeBind = {
["token"] = "132025-1378",
["stampedAt"] = "PLAYER_ENTERING_WORLD",
["restoredSession"] = 0,
["session"] = 1,
["boundAt"] = "ADDON_LOADED",
}
ForeverProbeClobber = {
["createdAt"] = "file-scope",
["boundAt"] = "ADDON_LOADED",
["stampedAt"] = "PLAYER_ENTERING_WORLD",
["restoredSession"] = 0,
["session"] = 1,
["token"] = "132025-1378",
}
ForeverProbeSeed = nil
