-- DocsVersion.lua
--
-- GENERATED by tools/build_reference.py (--docs-version) from the same capture
-- as reference/api/BUILD.md. Do not edit by hand; regenerate. It records the
-- client build the shipped API reference was generated from, so the addon can
-- tell a player when their client has moved on and the reference may be wrong.
--
-- This matters more here than it would in a shipped game. Blizzard moved this
-- beta from build 69893 to 69913 inside a single day, so a reference that is
-- slightly behind the client is the NORMAL case, not an edge case. The warning
-- is deliberately not silenced by default for that reason.
--
-- Counts are carried so the warning can say what the reference actually covers
-- rather than only naming a build number.

ForeverProbeDocsVersion = {
    version   = "1.60.1",
    build     = "70009",
    interface = 16001,
    generated = "2026-09-24",
    systems   = 410,
    functions = 6596,
    events    = 1805,
    tables    = 797,
}
