<#
.SYNOPSIS
  Write a payload into the INSTALLED ForeverProbe\BridgeData.lua, the inbound half
  of the bridge.

.DESCRIPTION
  The WoW client has no io, no os and no sockets, so the only way to hand a running
  addon data from outside is to write a .lua file the .toc already lists and let the
  client execute it as addon code at load. This is the mechanism the TSM desktop app
  uses (TradeSkillMaster_AppHelper\AppData.lua); see docs/auction-addon-architecture.md
  section 5.

  This writes into the GAME folder, not the repo, so that .\scripts\install-addon.ps1
  and this script do not fight over the same file.

  The channel is read once, at load. After writing, /reload in game and run
  /fprobe bridge to confirm the payload arrived.

.EXAMPLE
  .\scripts\write-bridge-data.ps1 -Message "hello from Claude Code"
  .\scripts\write-bridge-data.ps1 -Tag "notify" -Message "build finished" -Message2 "3 tests failed"
  .\scripts\write-bridge-data.ps1 -Reset
#>
[CmdletBinding()]
param(
    [string]$WowRoot,
    [string]$Flavor  = "_beta_",
    [string]$Addon   = "ForeverProbe",
    [string]$Tag     = "claude",
    [string]$Message = "hello from Claude Code",
    [string]$Message2,
    [switch]$Reset
)

$ErrorActionPreference = "Stop"

if (-not $WowRoot) {
    $candidates = @(
        "C:\Program Files (x86)\World of Warcraft",
        "C:\Program Files\World of Warcraft",
        "D:\World of Warcraft",
        "D:\Games\World of Warcraft",
        "E:\World of Warcraft",
        "F:\World of Warcraft",
        "F:\Games\World of Warcraft"
    )
    $WowRoot = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
}
if (-not $WowRoot -or -not (Test-Path $WowRoot)) {
    Write-Error "Could not find the WoW install. Pass -WowRoot explicitly."
}

$dest = Join-Path $WowRoot "$Flavor\Interface\AddOns\$Addon"
if (-not (Test-Path $dest)) {
    Write-Error "$Addon is not installed at $dest. Run .\scripts\install-addon.ps1 first."
}
$target = Join-Path $dest "BridgeData.lua"

# Lua long-bracket strings, so a payload containing quotes or backslashes needs no
# escaping. Refuse a payload that contains the closing bracket rather than
# generating a file that will not parse.
$payload = @($Message)
if ($Message2) { $payload += $Message2 }
foreach ($p in $payload) {
    if ($p -match "\]\]") { Write-Error "Payload may not contain ']]' - it would close the Lua string." }
}

if ($Reset) {
    $body = 'ns.LoadBridgeData("default", "unmodified")'
} else {
    $stamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $luaArgs = @("[[$Tag]]", "[[$stamp]]") + ($payload | ForEach-Object { "[[$_]]" })
    $body    = "ns.LoadBridgeData(" + ($luaArgs -join ", ") + ")"
}

$content = @"
-- Generated by scripts\write-bridge-data.ps1 at $((Get-Date).ToString("s")).
-- Overwritten freely: this file is the inbound channel, not source.
local _, ns = ...
if not ns or not ns.LoadBridgeData then return end

$body
"@

# UTF-8 without a BOM: luac and luajit both refuse a BOM, and the install
# script syntax-gates every .lua file it copies.
[System.IO.File]::WriteAllText($target, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $target" -ForegroundColor Green
Write-Host $body
Write-Host ""
Write-Host "In game: /reload  then  /fprobe bridge" -ForegroundColor Cyan
